### ISSUE TITLE
Review how Airflow example DAGs are loaded into the deployment

### ISSUE THREAD

**Issue by IsFlwrs** [wizeline-sre/aws-ec2-airflow-terraform#20]
We are interested to deploy particular DAG examples from the [Airflow repository](https://github.com/apache/airflow/tree/master/airflow/example_dags) into the Terraform deployment

**Comment by csmc88** [comment]
The [example_dags variable](https://github.com/wizeline-sre/aws-ec2-airflow-terraform/blob/d5aea2607d227f16e5a70251d33efbe57e586757/IaC/variables.tf#L98) is actually being passed on to Airflow's Scheduler through an [environment variable of the same name](https://github.com/wizeline-sre/aws-ec2-airflow-terraform/blob/d5aea2607d227f16e5a70251d33efbe57e586757/IaC/files/.env.airflow#L5)

[Airflow uses this variable as a parameter](https://github.com/apache/airflow/blob/311140616daafe496310d642e4164bc53fbd2ad2/airflow/models/dagbag.py#L90) during the scheduler execution to load the example dags within the standard installation. 

This means the flag is actually a "all examples" or "no examples" instead of a selection of a subset.

**Comment by csmc88** [comment]
Closing this ticket
